#!/usr/bin/env bash
set -e

check-minikube-installed() {
  if [ ! -x "$(command -v minikube)" ]; then
    echo "[-] Minikube not installed. Please use the minikube/install.sh script to install first."
    exit 1
  elif [ -z "$(minikube status | grep "apiserver: Running")" ]; then
    echo "[-] Minikube is installed but the cluster is not running.
Please use the minikube/install.sh script to install first."
    exit 1
  else
    echo "[+] Prerequisite minikube is installed"
  fi
}
