apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: time-service-canary
  namespace: time-service
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: time-service
  service:
    port: 3000
  analysis:
    interval: 10s
    threshold: 5
    stepWeight: 10
    maxWeight: 100
    metrics:
      - name: request-success-rate
        thresholdRange:
          max: 500
        interval: 1m
